# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

## CI Start
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  pathtosolution: 'PizzaBox/'
  pathtoproject: 'PizzaBox/PizzaBox.Client'
  pathtotest: 'PizzaBox/PizzaBox.Testing'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'P1SCSonarServiceConnection'
    organization: 'ordera'
    scannerMode: 'MSBuild'
    projectKey: 'p1-shaanan-curtis'
    projectName: 'p1-shaanan-curtis'
    extraProperties: |
      sonar.cs.opencover.reportsPaths="$(Build.ArtifactStagingDirectory)/coverage/*"
      sonar.cs.vstest.reportsPaths="$(Build.ArtifactStagingDirectory)/test/*.trx"
      sonar.exclusions=**/wwwroot/lib/**/*
- script: 
    dotnet build --configuration $(buildConfiguration)
  workingDirectory: $(pathtosolution)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test
    --configuration $(buildConfiguration)
    --logger trx
    --no-build
    --results-directory $(Build.ArtifactStagingDirectory)/test/
    /p:CollectCoverage=true
    /p:CoverletOutputFormat=opencover
    /p:CoverletOutput="$(Build.ArtifactStagingDirectory)/coverage/"
  workingDirectory: $(pathtosolution)
  displayName: 'dotnet test'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(pathtotest)'
    workingDirectory: '$(pathtosolution)'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: --configuration $(buildConfiguration)
    publishWebProjects: true
    zipAfterPublish: true
    workingDirectory: '$(pathtosolution)'
  displayName: 'dotnet publish + zip'
####--- CI END

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(396ce4c5-bc45-4835-91e3-1354d6969b00)'
    appType: 'webAppLinux'
    appName: 'PizzaboxCo'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'